ruamk/carma

tools/builder.sh

Helps to see which command log message belongs to when running all tasks in parallel.

tools/builder.sh: Parallel log

---

.circleci/config.yml
.editorconfig
README.md
carma-models/package.yaml
carma-models/src/Carma/Model/DiagSlide.hs
carma-models/src/Carma/Model/DiagSlide/Persistent.hs
carma-models/src/Carma/Model/LegacyTypes.hs
carma-models/src/Database/Persist/Postgresql/JSON.hs
srv/resources/assets/pure/src/App/Store/DiagTree/Editor/Actions.purs
srv/resources/assets/pure/src/App/Store/DiagTree/Editor/Handlers.purs
srv/resources/assets/pure/src/App/Store/DiagTree/Editor/Handlers/CopySlide.purs
srv/resources/assets/pure/src/App/Store/DiagTree/Editor/Handlers/CutSlide.purs
srv/resources/assets/pure/src/App/Store/DiagTree/Editor/Handlers/PasteSlide.purs
srv/resources/assets/pure/src/App/Store/DiagTree/Editor/Reducers.purs
srv/resources/assets/pure/src/Component/DiagTree/Editor.purs
srv/resources/assets/pure/src/Component/DiagTree/Editor/Tree.purs
srv/resources/assets/pure/src/Component/DiagTree/Editor/Tree/Item.purs
srv/resources/assets/pure/src/Component/DiagTree/Editor/Tree/Item.styl
srv/resources/assets/pure/src/Utils.purs
srv/resources/assets/pure/src/Utils/CopyPasteBuffer.purs
srv/src/AppHandlers/DiagTree.hs
srv/src/ApplicationInit.hs
tools/builder.sh

- Copying/moving `DiagTree` branch feature

Release 09.11.2018

---

srv/src/AppHandlers/Users.hs

1. __carma__: checking user activeness in check-auth helpers.
If a user is not active 403 will be returned.

Release 25.01.2019

---

carma-models/src/Carma/Model/VinFormat/Persistent.hs
srv/devel.cfg
srv/resources/assets/pure/package-lock.json
srv/resources/assets/script/screens/vin.coffee
srv/resources/assets/template/screens/vin.pug
srv/src/AppHandlers/Bulk.hs
srv/src/ApplicationInit.hs
stack.yaml
tools/vinnie/src/Carma/VIN.hs
tools/vinnie/src/Carma/VIN/SQL.hs

- Feature: uploading VIN contracts from directory

Release 22.02.2019

---

srv/resources/assets/script/screens/dictionaries.coffee

- Fix for hidden new users.
_P.S. We urged to fix ad-hoc for dictionaries elements limit._

Release 04.03.2019

---

README.md
carma-nominatim-mediator/src/Carma/NominatimMediator/Types.hs

- `carma-nominatim-mediator`: fixed data model (type were updated on the nominatim side)

Release 17.03.2019

---

caroperator-svc/LICENSE
caroperator-svc/Main.hs
caroperator-svc/README.md
caroperator-svc/cert.sh
caroperator-svc/install.sh

- Fix: removed `sellDate` ad-hoc range limit from `caroperator-svc`
- Improvements for documentation of `caroperator-svc`

Release 22.03.2019

---

srv/src/ApplicationHandlers.hs

Increase limit of DiagSlides loaded into web page.

Increase limit of DiagSlides loaded.

---

carma-era-glonass-integration/package.yaml
carma-era-glonass-integration/src/Carma/EraGlonass/Helpers.hs
carma-era-glonass-integration/src/Carma/EraGlonass/Model/CaseEraGlonassFailure.hs
carma-era-glonass-integration/src/Carma/EraGlonass/Model/CaseEraGlonassFailure/Persistent.hs
carma-era-glonass-integration/src/Carma/EraGlonass/Model/Types.hs
carma-era-glonass-integration/src/Carma/EraGlonass/Server.hs
carma-era-glonass-integration/src/Carma/EraGlonass/Server/ReceiveRequestForServiceRequest.hs
carma-era-glonass-integration/src/Carma/EraGlonass/Types/EGRequestForServiceRequest.hs
carma-era-glonass-integration/src/Carma/EraGlonass/VinSynchronizer.hs
carma-era-glonass-integration/src/Carma/EraGlonass/VinSynchronizer/Helpers.hs
carma-era-glonass-integration/src/Carma/EraGlonass/VinSynchronizer/SynchronizeContracts.hs
carma-era-glonass-integration/src/Carma/EraGlonass/VinSynchronizer/UnmarkAsHandled.hs
carma-models/src/Carma/Model/Types.hs
carma-monads/package.yaml
carma-monads/src/Carma/Monad.hs
carma-monads/src/Carma/Monad/Esqueleto.hs
carma-utils/src/Carma/Utils/TypeSafe/TypeFamilies.hs
database/patches/1.349.2-era-glonass-failure-model-repeats.sql
srv/resources/assets/script/screens/partners.coffee
srv/src/ApplicationHandlers.hs

* srv:
* fix bug: increase limit of Partners loaded.
* Changes for feature/carma-era-glonass-integration (only merge without deploy)

Release 19.08.2019

---

srv/src/Triggers.hs

Increase expected and real end time for towage by tech support request.

Increase expected and real end time for towage.

---

srv/src/Triggers.hs

Release increase of towage time parameters.

Release 2019.10.15

---

carma-era-glonass-integration/app.cfg.default
carma-era-glonass-integration/src/Carma/EraGlonass/App.hs
carma-era-glonass-integration/src/Carma/EraGlonass/Server.hs
carma-era-glonass-integration/src/Carma/EraGlonass/StatusSynchronizer.hs
carma-era-glonass-integration/src/Carma/EraGlonass/Types/AppContext.hs
carma-era-glonass-integration/src/Carma/EraGlonass/Types/TurnedOffResponse.hs
carma-era-glonass-integration/src/Carma/EraGlonass/VinSynchronizer.hs

- `carma-era-glonass-integration`: add ability to turn off vin/status synchronizer by config file

Release 31.10.2019

---

srv/resources/assets/script/screens/vin.coffee
srv/resources/assets/template/screens/vin.pug
srv/src/AppHandlers/Bulk.hs

Show "Import from directory" button for vinAdmin role only.

Release 13.11.2019

---

srv/resources/assets/script/screens/vin.coffee

frontend:
* Fix bug with double event handler for 'Import from directory' button.

Release 09.12.2019

---

srv/resources/assets/script/dictionaries/computed-dict.coffee
srv/src/ApplicationHandlers.hs

* carma
* Increase number of Partners available in backend and frontend.

Release 23.04.2020

---

database/baseline/1-tables/3-Event.sql
database/baseline/1-tables/5-PartnerCancel.sql
database/baseline/3-dictionaries/27-Sms.sql
database/baseline/3-dictionaries/63-AvayaEvent.sql
database/baseline/4-indexes.sql
database/patches/1.350.0-faster-case-history.sql

* Makes queries on "CaseHistory" runs faster.

Release 28.04.2020

---

location-sharing-svc/debian/location-sharing-svc.upstart
location-sharing-svc/src/Main.hs

- `chdir` in upstart
- `setLocale` in service

Fix location svc

---

srv/src/ApplicationHandlers.hs

Move select limit constants to .cfg file.

Move constants to .cfg file.

---

carma-models/src/Carma/Model/Case.hs
carma-models/src/Carma/Model/Case/Type.hs
database/baseline/3-dictionaries/81-Autoteka.sql
database/patches/1.356.0-autoteka-tables.sh
database/patches/1.356.1-autoteka-permissions.sql
srv/package-lock.json
srv/package.yaml
srv/resources/assets/script/hooks/case.coffee
srv/resources/assets/script/hooks/config.coffee
srv/resources/assets/template/fields/form.pug
srv/snaplets-default/autoteka/devel.cfg
srv/src/Application.hs
srv/src/ApplicationInit.hs
srv/src/Snaplet/Autoteka.hs
stack.yaml
stack.yaml.lock

Получение данных по госномеру из автотеки

---

carma-models/src/Carma/Model/VinFormat.hs
carma-models/src/Carma/Model/VinFormat/Meta.hs
tools/vinnie/src/Carma/VIN.hs
tools/vinnie/src/Carma/VIN/SQL.hs

Reverts ruamk/carma#66.
Because make is optional.

Revert "Fix bug - import contract now correctly recognize model depending on …"

---

carma-models/src/Carma/Model/VinFormat.hs
carma-models/src/Carma/Model/VinFormat/Meta.hs
tools/vinnie/src/Carma/VIN.hs
tools/vinnie/src/Carma/VIN/SQL.hs

Reverts ruamk/carma#67
Because make is optional.

Revert "Release 29.09.2020"

---

srv/resources/assets/script/screens/contract.coffee

Remove warning about 7 years restriction form BMW SARA program in frontend.

Remove warning about 7 years restriction for BMW SARA program.

---

carma-models/src/Carma/Model/Case.hs
srv/resources/assets/script/hooks/case.coffee
srv/resources/assets/template/fields/form.pug
srv/src/Snaplet/Autoteka.hs

* add autosearch for plate number in autoteka.
* carma

Release 27.10.2020

---

carma-mobile-server/src/Application.hs

Fix remote carma host for carma-mobile-server.

Fix carma hostname for carma-mobile-server.

---

carma-mobile-server/src/Application.hs
carma-models/src/Carma/Model/Case.hs
srv/resources/assets/script/hooks/case.coffee
srv/src/Snaplet/Autoteka.hs
srv/src/Triggers.hs

* Fix carma hostname for carma-mobile-server
* Fix plate num for autoteka
* carma

Release 19.10.2020

---

srv/resources/assets/template/screens/printSrv.pug

Add missing fields to print template.

Fix template with new fields.

---

carma-casepartner-us/src/AppHandlers/MobileAPI.hs
carma-casepartner-us/src/AppHandlers/Service.hs
carma-casepartner-us/src/Types.hs

Add missing first and last locations in case partner backend for UI.

Add first and last locations in service description for case partner UI.

---

carma-casepartner-fe/elm.json
carma-casepartner-fe/public/caret-down-fill.svg
carma-casepartner-fe/public/caret-right-fill.svg
carma-casepartner-fe/public/plus-square.svg
carma-casepartner-fe/src/Api.elm
carma-casepartner-fe/src/Pages/ShowService.elm
carma-casepartner-fe/src/Types.elm
carma-casepartner-fe/src/Utils.elm
carma-casepartner-us/src/AppHandlers/MobileAPI.hs
carma-casepartner-us/src/AppHandlers/Service.hs
carma-casepartner-us/src/Service/Util.hs
carma-casepartner-us/src/Site.hs
carma-casepartner-us/src/Types.hs
carma-casepartner-us/src/Util.hs
carma-utils/src/Carma/Utils/Snap.hs

* carma-casepartner-us
* Add UI and backend to manipulate photos with browser.

Release 2012-03-18

---

carma-casepartner-us/devel.cfg
carma-casepartner-us/src/Service/Util.hs
carma-casepartner-us/src/Types.hs
srv/package-lock.json

* carma-casepartner-us
* Fix photo size 
* Fix js dependency security fix
* Fix invalid carma coord parse.

Release 2012.03.31

---

carma-models/src/Carma/Model/Partner.hs
carma-models/src/Carma/Model/Partner/Persistent.hs
database/patches/1.360.0-new-partner-fields.sql
srv/resources/assets/script/screens/partners.coffee

Add new fields into Partner model.

Add new fields to Partner model: isPartner, legalName and inn.
